server:
  port: 8081
spring:
  application:
    name: ddd-demo
  datasource:
    druid:
      max-active: 100
      query-timeout: 50
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/ddd_demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

dubbo:
  scan:
    base-packages: com.souche.ddddemo.gateway.ohs.api.rpc
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml